/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Thunk3D (https://sketchfab.com/Lily.Qin1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/face-5f3a5ed7db6a4a1186ef8634b3bfd042
Title: Face
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const FaceModel = (props) => {
  const { nodes, materials } = useGLTF('/models/face.glb')
  return (
    <group {...props} dispose={null} scale={0.9}>
      <group position={[20, 0, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.material_0}
          material-color={'#303a34'}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  )
}
export default FaceModel
// useGLTF.preload('/face.glb')
